#!/bin/sh
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

if [ -z "$COMMIT_SOURCE" ] || [ "$COMMIT_SOURCE" = "message" ] || [ "$COMMIT_SOURCE" = "template" ]; then
  MSG=$(cat "$COMMIT_MSG_FILE")
  if ! echo "$MSG" | grep -q "Husky"; then
    printf "%s\n\n⚡ 이번 커밋은 Husky를 사용해 자동 검증되었습니다." "$MSG" > "$COMMIT_MSG_FILE"
  fi
fi
